name: ci
on:
  schedule:
    - cron: "1/5 * * * *"
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:

permissions:
  contents: read

jobs:
  plugin-ci:
    uses: mickmister/mattermost-github-actions-workflows/.github/workflows/plugin-ci.yml@287e78a3d6ff64af791837c69747926774f1ea1a
    secrets: inherit
